FROM node:10-alpine as Build
WORKDIR /app
COPY package*.json /app/
RUN npm install

FROM node:10-alpine as Delivery
WORKDIR /usr/src/app
ENV PATH=/app/node_modules/.bin:$PATH
COPY --from=Build /app/node_modules/ /app/node_modules/
COPY . .
CMD ["node", "server.js"]


