FROM node:10-alpine as Build
WORKDIR /usr/src/app
COPY package*.json /usr/src/app
RUN npm install

FROM node:10-alpine as Delivery
WORKDIR /usr/src/app
ENV PATH=/usr/src/app/node_modules/.bin:$PATH
COPY --from=Build /usr/src/app/node_modules/ /usr/src/app/node_modules/
COPY . .
CMD ["node", "server.js"]


